name: upload-artifact

on:
  workflow_call:
    inputs:
      artifact-name:
        description: "name of the artifact"
        required: true
        type: string
      artifact-path:
        description: "path to artifact folder"
        required: true
        type: string

jobs: 
  upload:
    runs-on: ubuntu-latest

    steps:
      - run: mkdir -p ./${{ inputs.artifact-path }}
      - run: echo artifact > ./${{ inputs.artifact-path }}/${{ inputs.artifact-name }}
      - uses: actions/upload-artifact@v4
        with:
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}