name: build-test-deploy

on:
  workflow_call:
    inputs:
      node-version:
        description: "node version"
        required: true
        type: string
      envname:
        description: "target env"
        required: true
        type: string
        default: "npd"

jobs: 
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: checkout repo
        uses: actions/checkout@v4
      - name: use node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - run: npm install

  test: 
    needs: build

    runs-on: ubuntu-latest

    steps: 
      - name: checkout repo
        uses: actions/checkout@v4
      - name: use node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      - run: echo "test"
  
  deploy: 
    needs: [build, test]
    environment: ${{ inputs.envname }}

    runs-on: ubuntu-latest

    steps: 
      - name: checkout repo
        uses: actions/checkout@v4
      - run: echo ${{ inputs.envname }}
