name: terraform

on:
  workflow_call:
    # inputs:
    #   artifact-name:
    #     description: "name of the artifact"
    #     required: true
    #     type: string
    #   artifact-path:
    #     description: "path to artifact folder"
    #     required: true
    #     type: string

jobs: 
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
            terraform_version: "^1.3.7"
            terraform_wrapper: false
      - name: terraform init
        run: terraform init
      - name: terraform format
        run: terraform fmt
      - name: terraform validate
        run: terraform validate
      - name: terraform plan -out=plan.tfplan
        run: terraform plan
      - uses: actions/upload-artifact@v4
        with:
          name: "tfplan"
          path: "plan.tfplan"
